### ISSUE TITLE
service/adapter 패키지명 applicatoin 디렉토리로 이동

### ISSUE THREAD

**Issue by jxmen** [jxmen-workspace/cs-ai-interviewer#40]
헥사고날 아키텍처에서는 application에 있는 것들이 Spring의 `@Service`들이 위치하고, domain/service에는 도메인 서비스가 들어간다. (application service와 domain service는 다르다.) 

현재 서비스에 AOP가 적용되어 있으므로 aop 패키지명도 변경해야 한다.

### ToDo

- [x] service/apater 패키지 application으로 이동
- [x] AOP 수정사항 변경
- [x] AOP 변경 이후 정상 작동 여부 로그로 확인
